// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestverifyallTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testverifyall() {
    driver.get("https://staging.cicle.app/");
    driver.manage().window().setSize(new Dimension(1552, 880));
    driver.findElement(By.cssSelector(".DashboardPage_DashboardPage__flex__2rA7e:nth-child(4) > .LinkNoDecor_Link__3DEkL:nth-child(2) p")).click();
    driver.findElement(By.cssSelector(".DashboardPage_DashboardPage__flex__2rA7e:nth-child(4) > .LinkNoDecor_Link__3DEkL:nth-child(2) .ImageMember_wrapper__ouMKB:nth-child(2) > .ImageMember_image__x7ApH")).click();
    driver.findElement(By.cssSelector(".MessageSnapshot_Message__3Tb5u:nth-child(2) .MessageSnapshot_bodySection__13OO-")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".fr-element"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>test</p>'}", element);
    }
    driver.findElement(By.cssSelector(".ChatButton_container__3Ua3q > .MuiSvgIcon-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".text-light"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".MuiBreadcrumbs-li:nth-child(3) span")).click();
    driver.findElement(By.cssSelector(".CardSnapshot_SmallCard__1TW01:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".ListContainer_ListContainer__outerList__1PG0-")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#listcard_content-2 .ModalLinkNoDecor_ModalLink__1zSCj"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".ListContainer_ListContainer__outerList__1PG0-")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".OverlayButton_container__3kxDV:nth-child(3) .ModalLinkNoDecor_ModalLink__1zSCj"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".ListContainer_ListContainer__outerList__1PG0-")).click();
    driver.findElement(By.cssSelector(".ListContainer_ListContainer__outerList__1PG0-")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#listcard_content-1 > .OverlayButton_container__3kxDV:nth-child(1) .ModalLinkNoDecor_ModalLink__1zSCj"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".ListContainer_ListContainer__outerList__1PG0-")).click();
    driver.findElement(By.cssSelector(".MuiBreadcrumbs-li:nth-child(3) span")).click();
    driver.findElement(By.cssSelector(".DocSnapshot_main__content__3WMk1 > p")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".fr-fic:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".CreateCommentForm_formInitial__3AVVg")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#moreParagraph-3 > .fr-svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".fr-element"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>test</p>'}", element);
    }
    driver.findElement(By.cssSelector(".Button_container__1WNuB")).click();
    driver.findElement(By.cssSelector(".MuiBreadcrumbs-li:nth-child(3) span")).click();
    {
      WebElement element = driver.findElement(By.linkText("Home"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.close();
  }
}
