// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Verifysigninpage2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void verifysigninpage2() {
    driver.get("https://staging.cicle.app/");
    driver.manage().window().setSize(new Dimension(1552, 880));
    driver.findElement(By.id("6110cbafca29534e50314344")).click();
    driver.findElement(By.id("6110cbafca29534e50314344")).click();
    driver.findElement(By.linkText("Cicle")).click();
    driver.findElement(By.cssSelector(".NavHeader_navMemberSection__ApwJH .ImageMember_image__x7ApH")).click();
    driver.findElement(By.cssSelector(".UserProfile_text__1qq9b > p")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".btn-danger > .Button_container__1WNuB")).click();
    driver.findElement(By.cssSelector(".NavIcon_box__1xEK_:nth-child(2) .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector(".BoxPopOver_BoxPopOver__1vCj0")).click();
    driver.findElement(By.cssSelector(".NotificationContainer_iconRight__3_wXB > .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector(".NavIcon_box__1xEK_:nth-child(1) > .NavIcon_icon__1nI8A")).click();
    driver.findElement(By.cssSelector(".MuiSvgIcon-root:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".BreadcrumbHeader_breadcrumbItem__2d5to > span")).click();
    driver.findElement(By.cssSelector(".DashboardPage_DashboardPage__flex__2rA7e:nth-child(4) .ShowLimitMembers_container__1aumA")).click();
    driver.findElement(By.cssSelector(".BreadcrumbHeader_breadcrumbItem__2d5to > span")).click();
  }
}
