// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class VerifydocsfileTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void verifydocsfile() {
    driver.get("https://staging.cicle.app/");
    driver.manage().window().setSize(new Dimension(816, 864));
    driver.findElement(By.cssSelector(".DashboardPage_DashboardPage__flex__2rA7e:nth-child(4) p")).click();
    driver.findElement(By.cssSelector(".BucketSnapshot_Folder__3vk5x")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".Doc_main__title__37T5Y > h1")).click();
    driver.findElement(By.cssSelector(".CreateCommentForm_formInitial__3AVVg")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#backgroundColor-1 > .fr-svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#emoticons-1 path")).click();
    driver.findElement(By.cssSelector(".fr-blink > img")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".fr-element"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Hello guys<span class=\"fr-emoticon fr-deletable fr-emoticon-img\" style=\"background: url(https://cdnjs.cloudflare.com/ajax/libs/emojione/2.0.1/assets/svg/1f601.svg);\">&nbsp;</span>&nbsp;</p>'}", element);
    }
    driver.findElement(By.cssSelector("form")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("form"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.cssSelector("#emoticons-1 path")).click();
    driver.findElement(By.cssSelector(".fr-blink > img")).click();
    driver.findElement(By.cssSelector(".Button_container__1WNuB")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#comment_6120e848bdd44c2ee9319c28 .CommentItem_discussSection__1_fte p"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.close();
  }
}
